# Generated by Django 3.2.6 on 2021-09-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_movie_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='index',
            new_name='index_id',
        ),
    ]
