# Generated by Django 3.2.6 on 2021-09-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_user_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recommend',
            name='index_id',
            field=models.IntegerField(default=0),
        ),
    ]
