# Generated by Django 3.2.6 on 2021-09-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_user_recommend_index_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_recommend',
            old_name='userId',
            new_name='user',
        ),
    ]
